### ISSUE TITLE
Alfred 4

### ISSUE THREAD

**Issue by jan-matthis** [alexlafroscia/tldr-alfred#9]
It would be great if the workflow was compatible with Alfred 4. I exported it from Alfred 3 and imported in Alfred 4. Queries do not return results.

**Comment by skibitsky** [comment]
Hello, @jan-matthis 
I upgraded this workflow to support Alfred 4 in #10

**Comment by jan-matthis** [comment]
Thanks a lot for the upgrade!

Unfortunately, I'm not managing to get TLDR to show up in Alfred 4: I pulled the repository to reflect today's merge of the PR, ran `npm install` and restarted Alfred. However, TLDR does not show up in the workflow view. `alfy-init` seems to have been executed (see below). 

Any hints of what I might try?

```
npm install

> @alexlafroscia/tldr-alfred-workflow@1.4.1 postinstall /Users/jm/GitHub/others/tldr-alfred
> alfy-init

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @alexlafroscia/tldr-alfred-workflow@1.4.1 No repository field.

audited 3344 packages in 3.581s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by alexlafroscia** [comment]
I'm not sure -- I also ran the installation instructions locally and it is working for me...

Can you run `alfa-init` again manually from inside the directory?

**Comment by jan-matthis** [comment]
@alexlafroscia: Running `./node_modules/.bin/alfy-init` manually again did the trick, thanks a lot!
